### ISSUE TITLE
Error message while calling HTMLSentenceTokenizer

### ISSUE THREAD

**Issue by cli0** [wardbradt/HTMLST#1]
While trying to run your example code I get the error:

```
Traceback (most recent call last):
  File "extract.py", line 4, in <module>
    parsed_sentences = HTMLSentenceTokenizer().feed(example_html_one)
TypeError: 'module' object is not callable
```

And it ultimately stems from this:

`HTMLSentenceTokenizer' is not callable `

that I get directly from the IDE (Pycharm).

**Comment by conorosully** [comment]
I have this same error? Do y'all know what is going on?

**Comment by conorosully** [comment]
The following workaround worked for me:
- Download HTMLSentenceTokenizer.py to your local repository
- Then change the example code to something like:

import HTMLSentenceTokenizer
sentence = HTMLSentenceTokenizer.HTMLSentenceTokenizer()
example_html_one = open('example_html_one.html', 'r').read()
parsed_sentences = sentence.feed(example_html_one)
print(parsed_sentences)

**Comment by gevezex** [comment]
Without the download method of @conorosully:

```
from htmlst import HTMLSentenceTokenizer
sentence = HTMLSentenceTokenizer.HTMLSentenceTokenizer()
example_html_one = open('example_html_one.html', 'r').read()
parsed_sentences = sentence.feed(example_html_one)
print(parsed_sentences)
```

**Comment by acrabb** [comment]
any other users seeing this tool missing large chunks of text?
looks great though :)
